INFO     mypy.apps.douyin2douyin.main:main.py:27 🟢 正在使用 [cookie_17688150852.txt] 发布作品，当前账号排序: [1]
INFO     mypy.apps.douyin2douyin.hot_douyin_handler:hot_douyin_handler.py:257 🟢 —来自：音乐榜单的第19个音乐《推开世界的门》
INFO     mypy.apps.douyin2douyin.hot_douyin_handler:hot_douyin_handler.py:259 🟢 music_id: 7341037944532192012
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-5' coro=<BaiduWenkuAigcHelper.gen_ppt() done, defined at /home/runner/work/Python/Python/mypy/lib/baidu/baidu_aigc.py:27> exception=TimeoutError('Page.wait_for_selector: Timeout 600000ms exceeded.\nCall log:\nwaiting for locator("#wkChatWrap") to be visible\n')>
Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/lib/baidu/baidu_aigc.py", line 102, in gen_ppt
    raise ex
  File "/home/runner/work/Python/Python/mypy/lib/baidu/baidu_aigc.py", line 86, in gen_ppt
    await new_page.wait_for_selector("#wkChatWrap")
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7812, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_page.py", line 373, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 600000ms exceeded.
Call log:
waiting for locator("#wkChatWrap") to be visible

ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-6' coro=<BaiduWenkuAigcHelper.gen_ppt() done, defined at /home/runner/work/Python/Python/mypy/lib/baidu/baidu_aigc.py:27> exception=TimeoutError('Page.wait_for_selector: Timeout 600000ms exceeded.\nCall log:\nwaiting for locator("#wkChatWrap") to be visible\n')>
Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/lib/baidu/baidu_aigc.py", line 102, in gen_ppt
    raise ex
  File "/home/runner/work/Python/Python/mypy/lib/baidu/baidu_aigc.py", line 86, in gen_ppt
    await new_page.wait_for_selector("#wkChatWrap")
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 7812, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_page.py", line 373, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 600000ms exceeded.
Call log:
waiting for locator("#wkChatWrap") to be visible

INFO     mypy.apps.douyin2douyin.hot_douyin_handler:hot_douyin_handler.py:188 🟢 所有过滤的限制条件都不满足，可以搬运
ERROR    mypy.apps.douyin2douyin.hot_douyin_handler:hot_douyin_handler.py:167 🔴 出现错误: 'xbogus'
Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/apps/douyin2douyin/hot_douyin_handler.py", line 134, in _get_douyin_music_video
    url += '&X-Bogus=' + xbogus['xbogus']
KeyError: 'xbogus'
ERROR    mypy.apps.douyin2douyin.hot_douyin_handler:hot_douyin_handler.py:270 🔴 获取热门视频失败: get_douyin_hot_music_video fail
Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/apps/douyin2douyin/hot_douyin_handler.py", line 262, in handle
    video_url = self._get_douyin_hot_music_video()
  File "/home/runner/work/Python/Python/mypy/apps/douyin2douyin/hot_douyin_handler.py", line 190, in _get_douyin_hot_music_video
    raise Exception('get_douyin_hot_music_video fail')
Exception: get_douyin_hot_music_video fail