INFO     mypy.apps.youtu2douyin.main:main.py:37 🟢 运行模式: manual
INFO     mypy.apps.youtu2douyin.main:main.py:39 🟢 video_url: https://www.youtube.com/watch?v=A8WVGxXHUuU
INFO     mypy.apps.youtu2douyin.tools:tools.py:44 🟢 开始对 /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/channel_record.json 视频列表按照 publish_date 进行降序排序
WARNING  mypy.apps.youtu2douyin.channel_loop:channel_loop.py:396 🟠 未发现 [香港VVI] 的频道配置，将使用默认配置: {'channel_url': '', 'channel_name': '', 'enable': True, 'with_videos': True, 'with_shorts': True, 'with_srt': True, 'publish_cfg': {}, 'videos': [], 'shorts': []}
INFO     mypy.apps.youtu2douyin.tools:tools.py:81 🟢 new video《香港优才移民计划有什么利弊吗？全方位分析》found, id: A8WVGxXHUuU, publish date: 2024-05-22 00:00:00
WARNING  mypy.apps.youtu2douyin.channel_loop:channel_loop.py:141 🟠 未发现频道 [香港VVI] 的发布配置，将采用默认发布配置
INFO     mypy.apps.youtu2douyin.channel_loop:channel_loop.py:164 🟢 -----> 开始下载第 1/1 个视频: https://youtube.com/watch?v=A8WVGxXHUuU
INFO     mypy.lib.youtube.video_handler:video_handler.py:279 🟢 ===== 获取视频 =====
INFO     mypy.lib.youtube.video_handler:video_handler.py:280 🟢 输出路径: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A
INFO     mypy.lib.youtube.video_handler:video_handler.py:291 🟢 ===== 下载视频资源 =====
INFO     mypy.lib.youtube.ytdlp_helper:ytdlp_helper.py:143 🟢 ----- 下载视频 -----
DEBUG    /home/runner/work/github-runner/github-runner/mypy/utils/tools.py:tools.py:235 🔵 正在执行命令: ['yt-dlp', '--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU']
ERROR    /home/runner/work/github-runner/github-runner/mypy/utils/tools.py:tools.py:263 🔴 命令: ['yt-dlp', '--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU'] 执行失败，输出: [debug] Command-line config: ['--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-6.5.0-1021-azure-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://youtube.com/watch?v=A8WVGxXHUuU
[youtube] A8WVGxXHUuU: Downloading webpage
[youtube] A8WVGxXHUuU: Downloading ios player API JSON
[youtube] A8WVGxXHUuU: Downloading android player API JSON
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig aGgzbd4WV97XxUvP7 => 7Tdy-kZPBgK0bA
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig QKnz0szTHeFJIGqPc => ifzOVNhUG2BV6A
[youtube] A8WVGxXHUuU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] A8WVGxXHUuU: Downloading 1 format(s): 137+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp
[ThumbnailsConvertor] Converting thumbnail "/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp -update 1 -bsf:v mjpeg2jpeg -movflags +faststart file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.jpg
Deleting original file /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp (pass -k to keep)
[debug] Invoking http downloader on "https://rr5---sn-p5qlsn7l.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsWlJ6yFkucP-PKDmAY&ip=74.249.14.168&id=o-ADz-XXfQnIv51sr3VxMXclJzzeLOp4_I1WdViWMcA_SU&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qlsn7l%2Csn-p5qddn7d&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=1913750&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=38615112&dur=69.166&lmt=1716378161291582&mt=1716731812&fvip=5&keepalive=yes&c=IOS&txp=6209224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgN2I0a08Zbjf-qLo_iB-1nmEyQVJ17zN5Xg1hdwMzG4ECIH3XoZ_9i18SGUwp0x4vZzPrqkgQjvjiCPNDsRv0BOz2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAO22TfqbV9ZnIqsWK-n5RWUKd1_bt8WgBW5cGWBXIgTNAiA41mfEAA2KXgX64vNzKQ4q4nM_9d7UkOVvLl2jv5vJPA%3D%3D"
[download] Destination: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.f137.mp4
[download] Download completed
[debug] Invoking http downloader on "https://rr5---sn-p5qddn7d.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsjaBKWLkucPgcuxoAU&ip=74.249.14.168&id=o-AFSe4EUJEBYfLo9kjhp7RTAk8Y--oH1kFGwk0nAbFXxo&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qddn7d%2Csn-p5qlsn7l&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=4252500&bui=AWRWj2RT2cUsfGisQa3VEYPiMBub6RvsjCqWkcSgL9tGJxUF0ioHeOXS_sBTPKzRWZX5iH9wnwCmrUCr&spc=UWF9f5IzQsKbAHiQNFhvvXZY9viLMos6xq9TC2v4xR7BOET1Xv752tY4gYK4&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=w1HGMmFzdDUiYDNsWSbw3lwQ&rqh=1&gir=yes&clen=1106746&dur=69.181&lmt=1716378160005362&mt=1716731812&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=6208224&n=ifzOVNhUG2BV6A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANYsJeneAihqU4XGaxHYH37Eo1F-sNeArmtr4kILkQ5WAiBhUjDj8Zo0PPWDX_o2zMYI8FkIQsOE2tBEJ2h9v6ML6A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgGM1EkrDYaLIrdui5ZXfHcjH5HLQ0nJIqny3fovhBTpYCIG5Lo5-8TTwbjQ7i1U4fUqDXxL9-oX7jv3uNxoDpukVN"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3430, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

NoneType: None
ERROR    mypy.apps.youtu2douyin.channel_loop:channel_loop.py:176 🔴 命令: ['yt-dlp', '--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU'] 执行失败，输出: [debug] Command-line config: ['--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-6.5.0-1021-azure-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://youtube.com/watch?v=A8WVGxXHUuU
[youtube] A8WVGxXHUuU: Downloading webpage
[youtube] A8WVGxXHUuU: Downloading ios player API JSON
[youtube] A8WVGxXHUuU: Downloading android player API JSON
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig aGgzbd4WV97XxUvP7 => 7Tdy-kZPBgK0bA
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig QKnz0szTHeFJIGqPc => ifzOVNhUG2BV6A
[youtube] A8WVGxXHUuU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] A8WVGxXHUuU: Downloading 1 format(s): 137+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp
[ThumbnailsConvertor] Converting thumbnail "/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp -update 1 -bsf:v mjpeg2jpeg -movflags +faststart file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.jpg
Deleting original file /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp (pass -k to keep)
[debug] Invoking http downloader on "https://rr5---sn-p5qlsn7l.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsWlJ6yFkucP-PKDmAY&ip=74.249.14.168&id=o-ADz-XXfQnIv51sr3VxMXclJzzeLOp4_I1WdViWMcA_SU&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qlsn7l%2Csn-p5qddn7d&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=1913750&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=38615112&dur=69.166&lmt=1716378161291582&mt=1716731812&fvip=5&keepalive=yes&c=IOS&txp=6209224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgN2I0a08Zbjf-qLo_iB-1nmEyQVJ17zN5Xg1hdwMzG4ECIH3XoZ_9i18SGUwp0x4vZzPrqkgQjvjiCPNDsRv0BOz2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAO22TfqbV9ZnIqsWK-n5RWUKd1_bt8WgBW5cGWBXIgTNAiA41mfEAA2KXgX64vNzKQ4q4nM_9d7UkOVvLl2jv5vJPA%3D%3D"
[download] Destination: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.f137.mp4
[download] Download completed
[debug] Invoking http downloader on "https://rr5---sn-p5qddn7d.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsjaBKWLkucPgcuxoAU&ip=74.249.14.168&id=o-AFSe4EUJEBYfLo9kjhp7RTAk8Y--oH1kFGwk0nAbFXxo&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qddn7d%2Csn-p5qlsn7l&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=4252500&bui=AWRWj2RT2cUsfGisQa3VEYPiMBub6RvsjCqWkcSgL9tGJxUF0ioHeOXS_sBTPKzRWZX5iH9wnwCmrUCr&spc=UWF9f5IzQsKbAHiQNFhvvXZY9viLMos6xq9TC2v4xR7BOET1Xv752tY4gYK4&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=w1HGMmFzdDUiYDNsWSbw3lwQ&rqh=1&gir=yes&clen=1106746&dur=69.181&lmt=1716378160005362&mt=1716731812&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=6208224&n=ifzOVNhUG2BV6A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANYsJeneAihqU4XGaxHYH37Eo1F-sNeArmtr4kILkQ5WAiBhUjDj8Zo0PPWDX_o2zMYI8FkIQsOE2tBEJ2h9v6ML6A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgGM1EkrDYaLIrdui5ZXfHcjH5HLQ0nJIqny3fovhBTpYCIG5Lo5-8TTwbjQ7i1U4fUqDXxL9-oX7jv3uNxoDpukVN"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3430, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/apps/youtu2douyin/channel_loop.py", line 171, in _download_video_and_publish
    video_title, video_fullpath = video_handler.get_video(
  File "/home/runner/work/github-runner/github-runner/mypy/lib/youtube/video_handler.py", line 293, in get_video
    download_video, zh_srt, en_srt = y2_api.download_media(with_srt)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/youtube/ytdlp_helper.py", line 165, in download_media
    self._download_video()
  File "/home/runner/work/github-runner/github-runner/mypy/lib/youtube/ytdlp_helper.py", line 162, in _download_video
    run_cmd(cmd)
  File "/home/runner/work/github-runner/github-runner/mypy/utils/tools.py", line 264, in run_cmd
    raise Exception(errmsg)
Exception: 命令: ['yt-dlp', '--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU'] 执行失败，输出: [debug] Command-line config: ['--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-6.5.0-1021-azure-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://youtube.com/watch?v=A8WVGxXHUuU
[youtube] A8WVGxXHUuU: Downloading webpage
[youtube] A8WVGxXHUuU: Downloading ios player API JSON
[youtube] A8WVGxXHUuU: Downloading android player API JSON
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig aGgzbd4WV97XxUvP7 => 7Tdy-kZPBgK0bA
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig QKnz0szTHeFJIGqPc => ifzOVNhUG2BV6A
[youtube] A8WVGxXHUuU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] A8WVGxXHUuU: Downloading 1 format(s): 137+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp
[ThumbnailsConvertor] Converting thumbnail "/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp -update 1 -bsf:v mjpeg2jpeg -movflags +faststart file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.jpg
Deleting original file /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp (pass -k to keep)
[debug] Invoking http downloader on "https://rr5---sn-p5qlsn7l.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsWlJ6yFkucP-PKDmAY&ip=74.249.14.168&id=o-ADz-XXfQnIv51sr3VxMXclJzzeLOp4_I1WdViWMcA_SU&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qlsn7l%2Csn-p5qddn7d&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=1913750&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=38615112&dur=69.166&lmt=1716378161291582&mt=1716731812&fvip=5&keepalive=yes&c=IOS&txp=6209224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgN2I0a08Zbjf-qLo_iB-1nmEyQVJ17zN5Xg1hdwMzG4ECIH3XoZ_9i18SGUwp0x4vZzPrqkgQjvjiCPNDsRv0BOz2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAO22TfqbV9ZnIqsWK-n5RWUKd1_bt8WgBW5cGWBXIgTNAiA41mfEAA2KXgX64vNzKQ4q4nM_9d7UkOVvLl2jv5vJPA%3D%3D"
[download] Destination: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.f137.mp4
[download] Download completed
[debug] Invoking http downloader on "https://rr5---sn-p5qddn7d.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsjaBKWLkucPgcuxoAU&ip=74.249.14.168&id=o-AFSe4EUJEBYfLo9kjhp7RTAk8Y--oH1kFGwk0nAbFXxo&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qddn7d%2Csn-p5qlsn7l&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=4252500&bui=AWRWj2RT2cUsfGisQa3VEYPiMBub6RvsjCqWkcSgL9tGJxUF0ioHeOXS_sBTPKzRWZX5iH9wnwCmrUCr&spc=UWF9f5IzQsKbAHiQNFhvvXZY9viLMos6xq9TC2v4xR7BOET1Xv752tY4gYK4&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=w1HGMmFzdDUiYDNsWSbw3lwQ&rqh=1&gir=yes&clen=1106746&dur=69.181&lmt=1716378160005362&mt=1716731812&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=6208224&n=ifzOVNhUG2BV6A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANYsJeneAihqU4XGaxHYH37Eo1F-sNeArmtr4kILkQ5WAiBhUjDj8Zo0PPWDX_o2zMYI8FkIQsOE2tBEJ2h9v6ML6A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgGM1EkrDYaLIrdui5ZXfHcjH5HLQ0nJIqny3fovhBTpYCIG5Lo5-8TTwbjQ7i1U4fUqDXxL9-oX7jv3uNxoDpukVN"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3430, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden


ERROR    mypy.apps.youtu2douyin.channel_loop:channel_loop.py:177 🔴 视频 https://youtube.com/watch?v=A8WVGxXHUuU 获取异常: 命令: ['yt-dlp', '--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU'] 执行失败，输出: [debug] Command-line config: ['--format', 'bv+ba', '--merge-output-format', 'mp4', '--output', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.mp4', '--write-thumbnail', '--convert-thumbnail', 'jpg', '--output', 'thumbnail:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU', '--quiet', '--no-warnings', '--verbose', 'https://youtube.com/watch?v=A8WVGxXHUuU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-6.5.0-1021-azure-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://youtube.com/watch?v=A8WVGxXHUuU
[youtube] A8WVGxXHUuU: Downloading webpage
[youtube] A8WVGxXHUuU: Downloading ios player API JSON
[youtube] A8WVGxXHUuU: Downloading android player API JSON
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig aGgzbd4WV97XxUvP7 => 7Tdy-kZPBgK0bA
[debug] Loading youtube-nsig.bc657243 from cache
[debug] [youtube] Decrypted nsig QKnz0szTHeFJIGqPc => ifzOVNhUG2BV6A
[youtube] A8WVGxXHUuU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] A8WVGxXHUuU: Downloading 1 format(s): 137+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp
[ThumbnailsConvertor] Converting thumbnail "/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp -update 1 -bsf:v mjpeg2jpeg -movflags +faststart file:/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.jpg
Deleting original file /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.webp (pass -k to keep)
[debug] Invoking http downloader on "https://rr5---sn-p5qlsn7l.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsWlJ6yFkucP-PKDmAY&ip=74.249.14.168&id=o-ADz-XXfQnIv51sr3VxMXclJzzeLOp4_I1WdViWMcA_SU&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qlsn7l%2Csn-p5qddn7d&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=1913750&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=38615112&dur=69.166&lmt=1716378161291582&mt=1716731812&fvip=5&keepalive=yes&c=IOS&txp=6209224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgN2I0a08Zbjf-qLo_iB-1nmEyQVJ17zN5Xg1hdwMzG4ECIH3XoZ_9i18SGUwp0x4vZzPrqkgQjvjiCPNDsRv0BOz2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAO22TfqbV9ZnIqsWK-n5RWUKd1_bt8WgBW5cGWBXIgTNAiA41mfEAA2KXgX64vNzKQ4q4nM_9d7UkOVvLl2jv5vJPA%3D%3D"
[download] Destination: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UC4cw8Y12uIvrh8eLwGA3n8A/A8WVGxXHUuU/A8WVGxXHUuU.f137.mp4
[download] Download completed
[debug] Invoking http downloader on "https://rr5---sn-p5qddn7d.googlevideo.com/videoplayback?expire=1716753884&ei=fEFTZsjaBKWLkucPgcuxoAU&ip=74.249.14.168&id=o-AFSe4EUJEBYfLo9kjhp7RTAk8Y--oH1kFGwk0nAbFXxo&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=tp&mm=31%2C29&mn=sn-p5qddn7d%2Csn-p5qlsn7l&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=4252500&bui=AWRWj2RT2cUsfGisQa3VEYPiMBub6RvsjCqWkcSgL9tGJxUF0ioHeOXS_sBTPKzRWZX5iH9wnwCmrUCr&spc=UWF9f5IzQsKbAHiQNFhvvXZY9viLMos6xq9TC2v4xR7BOET1Xv752tY4gYK4&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=w1HGMmFzdDUiYDNsWSbw3lwQ&rqh=1&gir=yes&clen=1106746&dur=69.181&lmt=1716378160005362&mt=1716731812&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=6208224&n=ifzOVNhUG2BV6A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANYsJeneAihqU4XGaxHYH37Eo1F-sNeArmtr4kILkQ5WAiBhUjDj8Zo0PPWDX_o2zMYI8FkIQsOE2tBEJ2h9v6ML6A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgGM1EkrDYaLIrdui5ZXfHcjH5HLQ0nJIqny3fovhBTpYCIG5Lo5-8TTwbjQ7i1U4fUqDXxL9-oX7jv3uNxoDpukVN"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3430, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden