INFO     mypy.apps.youtu2douyin.tools:tools.py:101 🟢 更新 /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/playlist_record.json 中的 videos 为较新的记录
INFO     mypy.apps.youtu2douyin.tools:tools.py:78 🟢 new video《Grammar challenge: 'Wish' & the past perfect》found, id: 0LQw4Px7J_g, publish date: 2024-03-12 00:00:00
WARNING  mypy.lib.youtube.core.base:base.py:106 🟠 playlist has no shorts
INFO     mypy.apps.youtu2douyin.tools:tools.py:116 🟢 更新频道视频内容到倒数第 1 个视频成功
INFO     mypy.apps.youtu2douyin.main:main.py:37 🟢 运行模式: once
INFO     mypy.apps.youtu2douyin.channel_loop:log.py:192 🟢 ========================================
INFO     mypy.apps.youtu2douyin.channel_loop:channel_loop.py:297 🟢 开始处理频道: [Grammar Challenge] [https://www.youtube.com/playlist?list=PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC]
INFO     mypy.apps.youtu2douyin.channel_loop:log.py:192 🟢 ========================================
INFO     mypy.apps.youtu2douyin.channel_loop:channel_loop.py:308 🟢 频道 [Grammar Challenge] 发现 0 条新 video
INFO     mypy.apps.youtu2douyin.channel_loop:channel_loop.py:168 🟢 -----> 开始下载第 1/1 个视频: https://youtube.com/watch?v=0LQw4Px7J_g
INFO     mypy.lib.youtube.video_handler:video_handler.py:285 🟢 ===== 获取视频 =====
INFO     mypy.lib.youtube.video_handler:video_handler.py:286 🟢 输出路径: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC
INFO     mypy.lib.youtube.video_handler:video_handler.py:297 🟢 ===== 下载视频资源 =====
INFO     mypy.lib.youtube.ytdlp_helper:ytdlp_helper.py:128 🟢 ----- 下载视频 -----
INFO     mypy.lib.youtube.y2_subtitle_handler:y2_subtitle_handler.py:34 🟢 ----- 下载字幕 -----
INFO     mypy.lib.subtitle.subtitle_handler:subtitle_handler.py:46 🟢 ----- 把同一时间的字幕合并到同一行输出到: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC/0LQw4Px7J_g/0LQw4Px7J_g_zh.srt
INFO     mypy.lib.subtitle.subtitle_handler:subtitle_handler.py:46 🟢 ----- 把同一时间的字幕合并到同一行输出到: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC/0LQw4Px7J_g/0LQw4Px7J_g_en.srt
INFO     mypy.lib.youtube.video_handler:video_handler.py:303 🟢 ===== 获取封面 =====
INFO     mypy.lib.youtube.video_handler:video_handler.py:266 🟢 封面图片上添加标题
INFO     mypy.lib.youtube.video_handler:video_handler.py:311 🟢 ===== 视频剪辑 =====
WARNING  mypy.lib.youtube.video_handler:video_handler.py:215 🟠 频道视频处理函数未实现，仅是拷贝源文件到目的路径下
INFO     mypy.lib.youtube.video_handler:video_handler.py:324 🟢 -----> 剪辑后视频路径: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC/0LQw4Px7J_g.mp4
DEBUG    mypy.apps.youtu2douyin.channel_loop:channel_loop.py:71 🔵 ----- 视频信息: {'id': '0LQw4Px7J_g', 'url': 'https://youtube.com/watch?v=0LQw4Px7J_g', 'title': "Grammar challenge: 'Wish' & the past perfect", 'publish_date': '2024-03-12 00:00:00', 'published': []}
INFO     mypy.lib.playwright.publish_handler:publish_handler.py:75 🟢 -----> 开始发布《/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC/0LQw4Px7J_g.mp4》到 ['douyin', 'wechat'] 平台
WARNING  mypy.lib.playwright.publish_handler:log.py:123 🟠 [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/douyin 下发现多个 cookie: ['/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/douyin/cookie_middle.json', '/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/douyin/cookie_test.json']
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - 默认选择第一个 cookie: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/douyin/cookie_middle.json
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - 正在使用 [/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/douyin/cookie_middle.json] 发布作品
WARNING  mypy.lib.proxy_pool.proxy_pool_helper:proxy_pool_helper.py:49 🟠 未找到可用的 深圳(https) 代理地址
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - 默认选择第一个 cookie: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/wechat/cookie_large.json
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - 正在使用 [/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/config/cookie/wechat/cookie_large.json] 发布作品
WARNING  mypy.lib.proxy_pool.proxy_pool_helper:proxy_pool_helper.py:49 🟠 未找到可用的 深圳(https) 代理地址
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - ============================================================
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - [DouyinVideoPublishHelper] 开始执行发布任务
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - ============================================================
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - ============================================================
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - [WechatPublishHelper] 开始执行发布任务
INFO     mypy.lib.playwright.publish_handler:log.py:120 🟢 [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - ============================================================
CRITICAL mypy.lib.playwright.publish_handler:log.py:129 ❌ [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - 账号登录状态已失效，正在跳出: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")

CRITICAL mypy.lib.playwright.publish_handler:log.py:129 ❌ [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - 《语法挑战：“愿望”和过去的完美》发布异常: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")

ERROR    mypy.lib.playwright.common:common.py:141 🔴 Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 81, in _check_login_status
    user_name = await self._get_logined_username(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 72, in _get_logined_username
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 68, in _get_logined_username
    user_name = await page.inner_text(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 10493, in inner_text
    await self._impl_obj.inner_text(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py", line 904, in inner_text
    return await self._main_frame.inner_text(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 618, in inner_text
    return await self._channel.send("innerText", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/common.py", line 139, in launch_browser_mgr
    yield browser, context, page
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 147, in publish_mission
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 131, in publish_mission
    await self._check_login_status(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 85, in _check_login_status
    raise CheckLoginStatusExp(original_exception=ex) from ex
mypy.lib.playwright.exceptions.CheckLoginStatusExp: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")

CRITICAL mypy.lib.playwright.publish_handler:log.py:129 ❌ [platform: wechat], [publish_file: 0LQw4Px7J_g.mp4] - 《语法挑战：“愿望”和过去的完美》发布异常: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")

CRITICAL mypy.lib.playwright.publish_handler:log.py:129 ❌ [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - 账号登录状态已失效，正在跳出: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")

CRITICAL mypy.lib.playwright.publish_handler:log.py:129 ❌ [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - 《语法挑战：“愿望”和过去的完美》发布异常: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")

ERROR    mypy.lib.playwright.common:common.py:141 🔴 Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 81, in _check_login_status
    user_name = await self._get_logined_username(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 72, in _get_logined_username
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 68, in _get_logined_username
    user_name = await page.inner_text(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 10493, in inner_text
    await self._impl_obj.inner_text(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py", line 904, in inner_text
    return await self._main_frame.inner_text(**locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 618, in inner_text
    return await self._channel.send("innerText", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/common.py", line 139, in launch_browser_mgr
    yield browser, context, page
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 147, in publish_mission
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 131, in publish_mission
    await self._check_login_status(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 85, in _check_login_status
    raise CheckLoginStatusExp(original_exception=ex) from ex
mypy.lib.playwright.exceptions.CheckLoginStatusExp: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")

CRITICAL mypy.lib.playwright.publish_handler:log.py:129 ❌ [platform: douyin], [publish_file: 0LQw4Px7J_g.mp4] - 《语法挑战：“愿望”和过去的完美》发布异常: Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")

WARNING  mypy.lib.playwright.publish_handler:publish_handler.py:58 🟠 [/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC/0LQw4Px7J_g.mp4] 发布到 [douyin] 失败，原因: [Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".rNsML")
]
WARNING  mypy.lib.playwright.publish_handler:publish_handler.py:58 🟠 [/home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_PLcetZ6gSk96_vxv0CWJGr7ySXLHnMXUpC/0LQw4Px7J_g.mp4] 发布到 [wechat] 失败，原因: [Page.inner_text: Timeout 120000ms exceeded.
Call log:
waiting for locator(".finder-nickname")
]
ERROR    mypy.apps.youtu2douyin.channel_loop:channel_loop.py:110 🔴 《Grammar challenge: 'Wish' & the past perfect》发布到 [douyin] 失败