INFO     mypy.apps.youtu2douyin.main:main.py:37 üü¢ ËøêË°åÊ®°Âºè: manual
INFO     mypy.apps.youtu2douyin.main:main.py:39 üü¢ video_url: https://www.youtube.com/watch?v=mAxFB3vbt7c
INFO     mypy.apps.youtu2douyin.tools:tools.py:78 üü¢ new video„ÄäOne of the world‚Äôs oldest condiments - Dan Kwartler„Äãfound, id: mAxFB3vbt7c, publish date: None
WARNING  mypy.apps.youtu2douyin.channel_loop:channel_loop.py:199 üü† Ëß£ÊûêÊó•ÊúüÂ≠óÁ¨¶‰∏≤ÂºÇÂ∏∏: time data 'None' does not match format '%Y-%m-%d %H:%M:%S'
INFO     mypy.apps.youtu2douyin.channel_loop:channel_loop.py:168 üü¢ -----> ÂºÄÂßã‰∏ãËΩΩÁ¨¨ 1/1 ‰∏™ËßÜÈ¢ë: https://youtube.com/watch?v=mAxFB3vbt7c
INFO     mypy.lib.youtube.y2_video_handler:y2_video_handler.py:285 üü¢ ===== Ëé∑ÂèñËßÜÈ¢ë =====
INFO     mypy.lib.youtube.y2_video_handler:y2_video_handler.py:286 üü¢ ËæìÂá∫Ë∑ØÂæÑ: /home/runner/work/github-runner/github-runner/mypy/tests/apps/youtu2douyin/_out/channel_UCsooa4yRKGN_zEE8iknghZA
ERROR    mypy.apps.youtu2douyin.channel_loop:channel_loop.py:179 üî¥ ERROR: [youtube] mAxFB3vbt7c: Sign in to confirm you‚Äôre not a bot. This helps protect our community. Learn more
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4468, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] mAxFB3vbt7c: Sign in to confirm you‚Äôre not a bot. This helps protect our community. Learn more

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/apps/youtu2douyin/channel_loop.py", line 175, in _download_video_and_publish
    video_title, video_fullpath = video_handler.get_video(
  File "/home/runner/work/github-runner/github-runner/mypy/lib/youtube/y2_video_handler.py", line 292, in get_video
    y2_api = YtdlpHelper(video_url=self._video_url,
  File "/home/runner/work/github-runner/github-runner/mypy/lib/youtube/ytdlp_helper.py", line 75, in __init__
    self._title, self._video_id, self._publish_date = get_video_info(
  File "/home/runner/work/github-runner/github-runner/mypy/lib/youtube/ytdlp_helper.py", line 62, in get_video_info
    info_dict = ydl.extract_info(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1644, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1092, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] mAxFB3vbt7c: Sign in to confirm you‚Äôre not a bot. This helps protect our community. Learn more
ERROR    mypy.apps.youtu2douyin.channel_loop:channel_loop.py:180 üî¥ ËßÜÈ¢ë https://youtube.com/watch?v=mAxFB3vbt7c Ëé∑ÂèñÂºÇÂ∏∏: ERROR: [youtube] mAxFB3vbt7c: Sign in to confirm you‚Äôre not a bot. This helps protect our community. Learn more