{"uid":"19698eebbddd225d","name":"test_wechat_publish_app[video]","fullName":"lib.wechat.test_wechat_publish_app#test_wechat_publish_app","historyId":"ecf6534a6d03007bde3a30c753929b00","time":{"start":1720238431724,"stop":1720238556237,"duration":124513},"status":"broken","statusMessage":"mypy.lib.playwright.exceptions.PublishFail: Page.inner_text: Timeout 120000ms exceeded.\nCall log:\nwaiting for locator(\".finder-nickname\")","statusTrace":"self = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\npage = <Page url='https://channels.weixin.qq.com/login.html'>\n\n    async def _check_login_status(self, page: Page):\n        \"\"\"\n        检查登录状态\n        \"\"\"\n        try:\n            # 登录\n            await page.goto(self._publish_playwright_cfg.creator_home_url)\n>           user_name = await self._get_logined_username(page)\n\nmypy/lib/playwright/publish_helper.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/playwright/publish_helper.py:73: in _get_logined_username\n    raise ex\nmypy/lib/playwright/publish_helper.py:69: in _get_logined_username\n    user_name = await page.inner_text(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/async_api/_generated.py:10493: in inner_text\n    await self._impl_obj.inner_text(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py:904: in inner_text\n    return await self._main_frame.inner_text(**locals_to_params(locals()))\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py:618: in inner_text\n    return await self._channel.send(\"innerText\", locals_to_params(locals()))\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x7f30f22e53d0>\ncb = <function Channel.send.<locals>.<lambda> at 0x7f3108648f70>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.inner_text: Timeout 120000ms exceeded.\nE           Call log:\nE           waiting for locator(\".finder-nickname\")\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py:514: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async with async_playwright() as playwright:\n>               await self.publish_mission(playwright)\n\nmypy/lib/playwright/publish_helper.py:155: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/utils/tools.py:450: in wrapper\n    async for attempt in AsyncRetrying(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/asyncio/__init__.py:166: in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/asyncio/__init__.py:153: in iter\n    result = await action(retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_utils.py:99: in inner\n    return call(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:398: in <lambda>\n    self._add_action_func(lambda rs: rs.outcome.result())\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:439: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:391: in __get_result\n    raise self._exception\nmypy/utils/tools.py:456: in wrapper\n    await async_func(*args, **kwargs)\nmypy/lib/playwright/publish_helper.py:147: in publish_mission\n    raise ex\nmypy/lib/playwright/publish_helper.py:131: in publish_mission\n    await self._check_login_status(page)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\npage = <Page url='https://channels.weixin.qq.com/login.html'>\n\n    async def _check_login_status(self, page: Page):\n        \"\"\"\n        检查登录状态\n        \"\"\"\n        try:\n            # 登录\n            await page.goto(self._publish_playwright_cfg.creator_home_url)\n            user_name = await self._get_logined_username(page)\n            self._logger.info('当前登录账号为 [%s]', user_name)\n        except Exception as ex:\n            self._logger.exception('账号登录状态已失效，正在跳出: %s', ex)\n>           raise CheckLoginStatusExp(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.CheckLoginStatusExp: Page.inner_text: Timeout 120000ms exceeded.\nE           Call log:\nE           waiting for locator(\".finder-nickname\")\n\nmypy/lib/playwright/publish_helper.py:86: CheckLoginStatusExp\n\nThe above exception was the direct cause of the following exception:\n\npublish_file = '/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_video_maked.mp4'\npublish_media_type = 'video'\n\n    @pytest.mark.parametrize(\n        'publish_file,publish_media_type',\n        [(Assets.ppt_video_maked, Const.MEDIA_TYPE_VIDEO)],\n        ids=[Const.MEDIA_TYPE_VIDEO])\n    def test_wechat_publish_app(publish_file, publish_media_type):\n        set_publish_cfg(config_path=config_path,\n                        option='media_type',\n                        value=publish_media_type)\n    \n>       WechatPublishApp(curr_dir).publish(\n            upload_filepath=publish_file)\n\nmypy/tests/lib/wechat/test_wechat_publish_app.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/playwright/publish_app.py:143: in publish\n    asyncio.run(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/runners.py:44: in run\n    return loop.run_until_complete(main)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py:647: in run_until_complete\n    return future.result()\nmypy/lib/playwright/publish_app.py:139: in async_publish\n    await publish_helper.do_publish()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async with async_playwright() as playwright:\n                await self.publish_mission(playwright)\n        except Exception as ex:\n            self._logger.exception('《%s》发布异常: %s',\n                                   self._pub_title, ex)\n>           raise PublishFail(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.PublishFail: Page.inner_text: Timeout 120000ms exceeded.\nE           Call log:\nE           waiting for locator(\".finder-nickname\")\n\nmypy/lib/playwright/publish_helper.py:159: PublishFail","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1720234153647,"stop":1720234153647,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir","time":{"start":1720238431722,"stop":1720238431724,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"mypy.lib.playwright.exceptions.PublishFail: Page.inner_text: Timeout 120000ms exceeded.\nCall log:\nwaiting for locator(\".finder-nickname\")","statusTrace":"self = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\npage = <Page url='https://channels.weixin.qq.com/login.html'>\n\n    async def _check_login_status(self, page: Page):\n        \"\"\"\n        检查登录状态\n        \"\"\"\n        try:\n            # 登录\n            await page.goto(self._publish_playwright_cfg.creator_home_url)\n>           user_name = await self._get_logined_username(page)\n\nmypy/lib/playwright/publish_helper.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/playwright/publish_helper.py:73: in _get_logined_username\n    raise ex\nmypy/lib/playwright/publish_helper.py:69: in _get_logined_username\n    user_name = await page.inner_text(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/async_api/_generated.py:10493: in inner_text\n    await self._impl_obj.inner_text(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_page.py:904: in inner_text\n    return await self._main_frame.inner_text(**locals_to_params(locals()))\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_frame.py:618: in inner_text\n    return await self._channel.send(\"innerText\", locals_to_params(locals()))\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x7f30f22e53d0>\ncb = <function Channel.send.<locals>.<lambda> at 0x7f3108648f70>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.inner_text: Timeout 120000ms exceeded.\nE           Call log:\nE           waiting for locator(\".finder-nickname\")\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_connection.py:514: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async with async_playwright() as playwright:\n>               await self.publish_mission(playwright)\n\nmypy/lib/playwright/publish_helper.py:155: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/utils/tools.py:450: in wrapper\n    async for attempt in AsyncRetrying(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/asyncio/__init__.py:166: in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/asyncio/__init__.py:153: in iter\n    result = await action(retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_utils.py:99: in inner\n    return call(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:398: in <lambda>\n    self._add_action_func(lambda rs: rs.outcome.result())\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:439: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:391: in __get_result\n    raise self._exception\nmypy/utils/tools.py:456: in wrapper\n    await async_func(*args, **kwargs)\nmypy/lib/playwright/publish_helper.py:147: in publish_mission\n    raise ex\nmypy/lib/playwright/publish_helper.py:131: in publish_mission\n    await self._check_login_status(page)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\npage = <Page url='https://channels.weixin.qq.com/login.html'>\n\n    async def _check_login_status(self, page: Page):\n        \"\"\"\n        检查登录状态\n        \"\"\"\n        try:\n            # 登录\n            await page.goto(self._publish_playwright_cfg.creator_home_url)\n            user_name = await self._get_logined_username(page)\n            self._logger.info('当前登录账号为 [%s]', user_name)\n        except Exception as ex:\n            self._logger.exception('账号登录状态已失效，正在跳出: %s', ex)\n>           raise CheckLoginStatusExp(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.CheckLoginStatusExp: Page.inner_text: Timeout 120000ms exceeded.\nE           Call log:\nE           waiting for locator(\".finder-nickname\")\n\nmypy/lib/playwright/publish_helper.py:86: CheckLoginStatusExp\n\nThe above exception was the direct cause of the following exception:\n\npublish_file = '/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_video_maked.mp4'\npublish_media_type = 'video'\n\n    @pytest.mark.parametrize(\n        'publish_file,publish_media_type',\n        [(Assets.ppt_video_maked, Const.MEDIA_TYPE_VIDEO)],\n        ids=[Const.MEDIA_TYPE_VIDEO])\n    def test_wechat_publish_app(publish_file, publish_media_type):\n        set_publish_cfg(config_path=config_path,\n                        option='media_type',\n                        value=publish_media_type)\n    \n>       WechatPublishApp(curr_dir).publish(\n            upload_filepath=publish_file)\n\nmypy/tests/lib/wechat/test_wechat_publish_app.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/playwright/publish_app.py:143: in publish\n    asyncio.run(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/runners.py:44: in run\n    return loop.run_until_complete(main)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py:647: in run_until_complete\n    return future.result()\nmypy/lib/playwright/publish_app.py:139: in async_publish\n    await publish_helper.do_publish()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.wechat.video.publish_helper.WechatPublishHelper object at 0x7f30f24e2eb0>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async with async_playwright() as playwright:\n                await self.publish_mission(playwright)\n        except Exception as ex:\n            self._logger.exception('《%s》发布异常: %s',\n                                   self._pub_title, ex)\n>           raise PublishFail(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.PublishFail: Page.inner_text: Timeout 120000ms exceeded.\nE           Call log:\nE           waiting for locator(\".finder-nickname\")\n\nmypy/lib/playwright/publish_helper.py:159: PublishFail","steps":[],"attachments":[{"uid":"ce14df5eaab916ce","name":"log","source":"ce14df5eaab916ce.txt","type":"text/plain","size":11629}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"copy_config_to_dir::finish_callback","time":{"start":1720238556729,"stop":1720238556730,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"lib.wechat"},{"name":"suite","value":"test_wechat_publish_app"},{"name":"host","value":"fv-az774-103"},{"name":"thread","value":"7994-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"lib.wechat.test_wechat_publish_app"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"publish_file","value":"'/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_video_maked.mp4'"},{"name":"publish_media_type","value":"'video'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"19698eebbddd225d.json","parameterValues":["'/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_video_maked.mp4'","'video'"]}