{"uid":"6f61da8af966511b","name":"test_publish_app[image_article]","fullName":"lib.douyin.test_douyin_publish_app#test_publish_app","historyId":"0b16c57dbfb134058a5b4956fdb2d79f","time":{"start":1717417584987,"stop":1717417993318,"duration":408331},"description":"\n    测试图文发布、视频发布\n    ","descriptionHtml":"<pre><code>测试图文发布、视频发布\n</code></pre>\n","status":"broken","statusMessage":"mypy.lib.playwright.exceptions.PublishFail: RetryError[<Future at 0x7fdcfd120970 state=finished raised PublishFail>]","statusTrace":"self = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\nplaywright = <playwright._impl._playwright.Playwright object at 0x7fdd14cfdd60>\n\n    async def publish_mission(self, playwright: Playwright):\n        \"\"\"\n        发布任务\n        \"\"\"\n        self._logger.info(\"=\" * 60)\n        self._logger.info('[%s] 开始执行发布任务', self.__class__.__name__)\n        self._logger.info(\"=\" * 60)\n    \n        # 浏览器上下文\n        browser, context, page = await PlaywrightCommon(\n            cookie_filepath=self._cookie_filepath,\n            headless=self._headless).launch_browser(playwright)\n        try:\n            # 判断登录状态\n            await self._check_login_status(page)\n    \n            # 上传发布内容\n>           await self.upload(page)\n\nmypy/lib/playwright/publish_helper.py:122: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/douyin/image_publish_helper.py:47: in upload\n    await super().upload(page, upload_url, upload_locator, upload_filepath)\nmypy/lib/douyin/publish_helper.py:349: in upload\n    raise ex\nmypy/lib/douyin/publish_helper.py:342: in upload\n    await page.click(upload_locator)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py:60: in __aexit__\n    await self._event.value\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._async_base.AsyncEventInfo object at 0x7fdcfd251490>\n\n    @property\n    async def value(self) -> T:\n>       return mapping.from_maybe_impl(await self._future)\nE       playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event \"filechooser\"\nE       =========================== logs ===========================\nE       waiting for event \"filechooser\"\nE       ============================================================\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py:35: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async for attempt in AsyncRetrying(\n                    stop=stop_after_attempt(LoginLocator.publish_retry_cnt),\n                    wait=wait_fixed(LoginLocator.publish_retry_interval),\n                    before_sleep=before_sleep_log(self._logger, logging.WARNING)):\n                with attempt:\n                    async with async_playwright() as playwright:\n>                       await self.publish_mission(playwright)\n\nmypy/lib/playwright/publish_helper.py:149: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\nplaywright = <playwright._impl._playwright.Playwright object at 0x7fdd14cfdd60>\n\n    async def publish_mission(self, playwright: Playwright):\n        \"\"\"\n        发布任务\n        \"\"\"\n        self._logger.info(\"=\" * 60)\n        self._logger.info('[%s] 开始执行发布任务', self.__class__.__name__)\n        self._logger.info(\"=\" * 60)\n    \n        # 浏览器上下文\n        browser, context, page = await PlaywrightCommon(\n            cookie_filepath=self._cookie_filepath,\n            headless=self._headless).launch_browser(playwright)\n        try:\n            # 判断登录状态\n            await self._check_login_status(page)\n    \n            # 上传发布内容\n            await self.upload(page)\n    \n            # 填写信息\n            await self.fill_publish_content(page)\n    \n            # 触发发布并检查是否发布成功\n            await self.publish_trigger(page)\n        except Exception as ex:\n            self._logger.exception('❌❌❌《%s》发布异常: %s',\n                                   self._pub_title, ex)\n>           raise PublishFail(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.PublishFail: Timeout 120000ms exceeded while waiting for event \"filechooser\"\nE           =========================== logs ===========================\nE           waiting for event \"filechooser\"\nE           ============================================================\n\nmypy/lib/playwright/publish_helper.py:132: PublishFail\n\nThe above exception was the direct cause of the following exception:\n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n>           async for attempt in AsyncRetrying(\n                    stop=stop_after_attempt(LoginLocator.publish_retry_cnt),\n                    wait=wait_fixed(LoginLocator.publish_retry_interval),\n                    before_sleep=before_sleep_log(self._logger, logging.WARNING)):\n\nmypy/lib/playwright/publish_helper.py:143: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py:123: in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py:110: in iter\n    result = await action(retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py:78: in inner\n    return fn(*args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 140587513632896: attempt #3; slept for 6.0; last result: failed (PublishFail Timeout 120000ms exceeded...========================\nwaiting for event \"filechooser\"\n============================================================)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7fdcfd120970 state=finished raised PublishFail>]\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:411: RetryError\n\nThe above exception was the direct cause of the following exception:\n\npublish_file = '/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_slide_images'\n\n    @pytest.mark.parametrize(\n        'publish_file',\n        [Assets.ppt_slide_image_dir, Assets.vertical_video, Assets.ppt_video_maked],\n        ids=[Const.MEDIA_TYPE_IMG_ARTICLE, 'vertical_video', 'ppt_video'])\n    def test_publish_app(publish_file):\n        \"\"\"\n        测试图文发布、视频发布\n        \"\"\"\n        media_type = Const.MEDIA_TYPE_VIDEO\n        if os.path.isdir(publish_file):\n            media_type = Const.MEDIA_TYPE_IMG_ARTICLE\n        set_publish_cfg(config_path=config_path,\n                        option='media_type',\n                        value=media_type)\n>       DouyinPublishApp(curr_dir).publish(\n            upload_filepath=publish_file)\n\nmypy/tests/lib/douyin/test_douyin_publish_app.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/playwright/publish_app.py:143: in publish\n    asyncio.run(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/runners.py:44: in run\n    return loop.run_until_complete(main)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py:647: in run_until_complete\n    return future.result()\nmypy/lib/playwright/publish_app.py:139: in async_publish\n    await publish_helper.do_publish()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async for attempt in AsyncRetrying(\n                    stop=stop_after_attempt(LoginLocator.publish_retry_cnt),\n                    wait=wait_fixed(LoginLocator.publish_retry_interval),\n                    before_sleep=before_sleep_log(self._logger, logging.WARNING)):\n                with attempt:\n                    async with async_playwright() as playwright:\n                        await self.publish_mission(playwright)\n        except Exception as ex:\n            self._logger.exception('❌❌❌《%s》发布异常: %s',\n                                   self._pub_title, ex)\n>           raise PublishFail(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.PublishFail: RetryError[<Future at 0x7fdcfd120970 state=finished raised PublishFail>]\n\nmypy/lib/playwright/publish_helper.py:153: PublishFail","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1717415271185,"stop":1717415271185,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir","time":{"start":1717417507196,"stop":1717417507197,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n    测试图文发布、视频发布\n    ","status":"broken","statusMessage":"mypy.lib.playwright.exceptions.PublishFail: RetryError[<Future at 0x7fdcfd120970 state=finished raised PublishFail>]","statusTrace":"self = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\nplaywright = <playwright._impl._playwright.Playwright object at 0x7fdd14cfdd60>\n\n    async def publish_mission(self, playwright: Playwright):\n        \"\"\"\n        发布任务\n        \"\"\"\n        self._logger.info(\"=\" * 60)\n        self._logger.info('[%s] 开始执行发布任务', self.__class__.__name__)\n        self._logger.info(\"=\" * 60)\n    \n        # 浏览器上下文\n        browser, context, page = await PlaywrightCommon(\n            cookie_filepath=self._cookie_filepath,\n            headless=self._headless).launch_browser(playwright)\n        try:\n            # 判断登录状态\n            await self._check_login_status(page)\n    \n            # 上传发布内容\n>           await self.upload(page)\n\nmypy/lib/playwright/publish_helper.py:122: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/douyin/image_publish_helper.py:47: in upload\n    await super().upload(page, upload_url, upload_locator, upload_filepath)\nmypy/lib/douyin/publish_helper.py:349: in upload\n    raise ex\nmypy/lib/douyin/publish_helper.py:342: in upload\n    await page.click(upload_locator)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py:60: in __aexit__\n    await self._event.value\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._async_base.AsyncEventInfo object at 0x7fdcfd251490>\n\n    @property\n    async def value(self) -> T:\n>       return mapping.from_maybe_impl(await self._future)\nE       playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event \"filechooser\"\nE       =========================== logs ===========================\nE       waiting for event \"filechooser\"\nE       ============================================================\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py:35: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async for attempt in AsyncRetrying(\n                    stop=stop_after_attempt(LoginLocator.publish_retry_cnt),\n                    wait=wait_fixed(LoginLocator.publish_retry_interval),\n                    before_sleep=before_sleep_log(self._logger, logging.WARNING)):\n                with attempt:\n                    async with async_playwright() as playwright:\n>                       await self.publish_mission(playwright)\n\nmypy/lib/playwright/publish_helper.py:149: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\nplaywright = <playwright._impl._playwright.Playwright object at 0x7fdd14cfdd60>\n\n    async def publish_mission(self, playwright: Playwright):\n        \"\"\"\n        发布任务\n        \"\"\"\n        self._logger.info(\"=\" * 60)\n        self._logger.info('[%s] 开始执行发布任务', self.__class__.__name__)\n        self._logger.info(\"=\" * 60)\n    \n        # 浏览器上下文\n        browser, context, page = await PlaywrightCommon(\n            cookie_filepath=self._cookie_filepath,\n            headless=self._headless).launch_browser(playwright)\n        try:\n            # 判断登录状态\n            await self._check_login_status(page)\n    \n            # 上传发布内容\n            await self.upload(page)\n    \n            # 填写信息\n            await self.fill_publish_content(page)\n    \n            # 触发发布并检查是否发布成功\n            await self.publish_trigger(page)\n        except Exception as ex:\n            self._logger.exception('❌❌❌《%s》发布异常: %s',\n                                   self._pub_title, ex)\n>           raise PublishFail(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.PublishFail: Timeout 120000ms exceeded while waiting for event \"filechooser\"\nE           =========================== logs ===========================\nE           waiting for event \"filechooser\"\nE           ============================================================\n\nmypy/lib/playwright/publish_helper.py:132: PublishFail\n\nThe above exception was the direct cause of the following exception:\n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n>           async for attempt in AsyncRetrying(\n                    stop=stop_after_attempt(LoginLocator.publish_retry_cnt),\n                    wait=wait_fixed(LoginLocator.publish_retry_interval),\n                    before_sleep=before_sleep_log(self._logger, logging.WARNING)):\n\nmypy/lib/playwright/publish_helper.py:143: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py:123: in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py:110: in iter\n    result = await action(retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py:78: in inner\n    return fn(*args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 140587513632896: attempt #3; slept for 6.0; last result: failed (PublishFail Timeout 120000ms exceeded...========================\nwaiting for event \"filechooser\"\n============================================================)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7fdcfd120970 state=finished raised PublishFail>]\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:411: RetryError\n\nThe above exception was the direct cause of the following exception:\n\npublish_file = '/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_slide_images'\n\n    @pytest.mark.parametrize(\n        'publish_file',\n        [Assets.ppt_slide_image_dir, Assets.vertical_video, Assets.ppt_video_maked],\n        ids=[Const.MEDIA_TYPE_IMG_ARTICLE, 'vertical_video', 'ppt_video'])\n    def test_publish_app(publish_file):\n        \"\"\"\n        测试图文发布、视频发布\n        \"\"\"\n        media_type = Const.MEDIA_TYPE_VIDEO\n        if os.path.isdir(publish_file):\n            media_type = Const.MEDIA_TYPE_IMG_ARTICLE\n        set_publish_cfg(config_path=config_path,\n                        option='media_type',\n                        value=media_type)\n>       DouyinPublishApp(curr_dir).publish(\n            upload_filepath=publish_file)\n\nmypy/tests/lib/douyin/test_douyin_publish_app.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/playwright/publish_app.py:143: in publish\n    asyncio.run(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/runners.py:44: in run\n    return loop.run_until_complete(main)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py:647: in run_until_complete\n    return future.result()\nmypy/lib/playwright/publish_app.py:139: in async_publish\n    await publish_helper.do_publish()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mypy.lib.douyin.image_publish_helper.DouyinImagesPublishHelper object at 0x7fdcfd22e220>\n\n    async def do_publish(self):\n        \"\"\"\n        发布任务，如果获取登录状态失败，则重试\n        \"\"\"\n        try:\n            async for attempt in AsyncRetrying(\n                    stop=stop_after_attempt(LoginLocator.publish_retry_cnt),\n                    wait=wait_fixed(LoginLocator.publish_retry_interval),\n                    before_sleep=before_sleep_log(self._logger, logging.WARNING)):\n                with attempt:\n                    async with async_playwright() as playwright:\n                        await self.publish_mission(playwright)\n        except Exception as ex:\n            self._logger.exception('❌❌❌《%s》发布异常: %s',\n                                   self._pub_title, ex)\n>           raise PublishFail(original_exception=ex) from ex\nE           mypy.lib.playwright.exceptions.PublishFail: RetryError[<Future at 0x7fdcfd120970 state=finished raised PublishFail>]\n\nmypy/lib/playwright/publish_helper.py:153: PublishFail","steps":[],"attachments":[{"uid":"b998da5b58b91d96","name":"log","source":"b998da5b58b91d96.txt","type":"text/plain","size":15080}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"copy_config_to_dir::finish_callback","time":{"start":1717418089213,"stop":1717418089214,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"douyin"},{"name":"parentSuite","value":"lib.douyin"},{"name":"suite","value":"test_douyin_publish_app"},{"name":"host","value":"fv-az777-346"},{"name":"thread","value":"7252-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"lib.douyin.test_douyin_publish_app"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"publish_file","value":"'/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_slide_images'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["douyin"]},"source":"6f61da8af966511b.json","parameterValues":["'/home/runner/work/github-runner/github-runner/mypy/assets/media/ppt/ppt_slide_images'"]}